[package]
name = "wasm_poly"
version = "0.1.0"
authors = ["Anton Lempiy <lempiyada@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
stdweb = "*"
serde = "1.0.0"
serde_derive = "1.0.0"
poly = {git='https://github.com/lempiy/Weiler-Atherton-Clipping.git'}
