[package]
name = "WasmGl"
version = "0.1.0"
authors = ["Anton Lempiy <lempiyada@gmail.com>"]

[dependencies]
stdweb = "*"
stdweb-derive = "*"
serde = "1.0.0"
serde_derive = "1.0.0"

[build-dependencies]
webgl_generator = "0.1.0"
